<a href="https://colab.research.google.com/github/kazaprasanth/pytorchintro/blob/main/pytorchintro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
import numpy as np

In [1]:
my_list = [1,2,3,4,5]
my_list

[1, 2, 3, 4, 5]

In [6]:
np1 = np.random.rand(3,4)
np1

array([[0.21588086, 0.76252471, 0.71486139, 0.42112944],
       [0.09334507, 0.04422655, 0.33661967, 0.93282994],
       [0.44788422, 0.26783517, 0.9129521 , 0.73161189]])

In [7]:
np1.dtype

dtype('float64')

In [9]:
tensor_2d = torch.randn(3,4)
tensor_2d

tensor([[ 0.6161, -0.1797, -1.1504, -0.4365],
        [ 0.2864, -0.4707, -0.3611, -1.4602],
        [ 0.4342,  1.2142, -0.4202,  0.4558]])

In [11]:
tensor_3d = torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [12]:
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.2159, 0.7625, 0.7149, 0.4211],
        [0.0933, 0.0442, 0.3366, 0.9328],
        [0.4479, 0.2678, 0.9130, 0.7316]], dtype=torch.float64)

In [13]:
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
my_torch = my_torch.reshape(2,5)
my_torch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [17]:
my_torch2 = torch.arange(15)
my_torch2

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [22]:
my_torch2 = my_torch2.reshape(-1,5)
my_torch2

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])

In [23]:
my_torch3 = torch.arange(10)
my_torch3

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
my_torch4 = my_torch3.view(2,5)
my_torch4

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [25]:
my_torch5 = torch.arange(10)
my_torch5

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
my_torch6 = my_torch5.reshape(2,5)
my_torch6

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [27]:
my_torch7 = torch.arange(10)
my_torch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [28]:
my_torch7

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
my_torch8 = my_torch7.reshape(5,2)
my_torch8

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [30]:
my_torch8[:,1:]

tensor([[1],
        [3],
        [5],
        [7],
        [9]])

In [3]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])


In [4]:
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [5]:
torch.add(tensor_a, tensor_b)

tensor([ 6,  8, 10, 12])

In [6]:

tensor_b - tensor_a

tensor([4, 4, 4, 4])

In [7]:
torch.sub(tensor_b , tensor_a)

tensor([4, 4, 4, 4])

In [8]:
tensor_a * tensor_b

tensor([ 5, 12, 21, 32])

In [10]:
torch.mul(tensor_a , tensor_b)

tensor([ 5, 12, 21, 32])

In [11]:
tensor_b/tensor_a

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [12]:
torch.div(tensor_b , tensor_a)

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [13]:
tensor_b % tensor_a

tensor([0, 0, 1, 0])

In [14]:
torch.remainder(tensor_b , tensor_a)

tensor([0, 0, 1, 0])

In [15]:
torch.pow(tensor_a, tensor_b)

tensor([    1,    64,  2187, 65536])

In [16]:
tensor_a.add(tensor_b)

tensor([ 6,  8, 10, 12])

In [17]:
tensor_a = tensor_a + tensor_b

In [18]:
tensor_a.add(tensor_b)

tensor([11, 14, 17, 20])

In [19]:
tensor_a

tensor([ 6,  8, 10, 12])

In [9]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [10]:
class Model(nn.Module):
  def __init__(self, in_features=4, h1=8, h2=9, out_features=3):
    super().__init__() #instantitate our nn.module
    self.fc1 = nn.Linear(in_features, h1)
    self.fc2 = nn.Linear(h1, h2)
    self.out = nn.Linear(h2, out_features)

def forward(self, x):
  x = F.relu(self.fc1(x))
  x = F.relu(self.fc2(x))
  x = self.out(x)

  return x




In [11]:
torch.manual_seed(41)
model = Model() #create an instance for model

In [13]:
import matplotlib.pyplot as plt
%matplotlib inline
import pandas as pd

In [14]:
url = 'https://gist.githubusercontent.com/curran/a08a1080b88344b0c8a7/raw/0e7a9b0a5d22642a06d3d5b9bcbad9890c8ee534/iris.csv'
my_df = pd.read_csv(url)

In [16]:
my_df.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [18]:
my_df['species'] = my_df['species'].replace('Setosa', 0.0)
my_df['species'] = my_df['species'].replace('versicolor', 1.0)
my_df['species'] = my_df['species'].replace('virginica', 2.0)

In [19]:
my_df

sepal_length  sepal_width  petal_length  petal_width species
0             5.1          3.5           1.4          0.2  setosa
1             4.9          3.0           1.4          0.2  setosa
2             4.7          3.2           1.3          0.2  setosa
3             4.6          3.1           1.5          0.2  setosa
4             5.0          3.6           1.4          0.2  setosa
..            ...          ...           ...          ...     ...
145           6.7          3.0           5.2          2.3     2.0
146           6.3          2.5           5.0          1.9     2.0
147           6.5          3.0           5.2          2.0     2.0
148           6.2          3.4           5.4          2.3     2.0
149           5.9          3.0           5.1          1.8     2.0

[150 rows x 5 columns]

In [20]:
x = my_df.drop('species', axis=1)
y = my_df['species']

In [21]:
x = x.values
y = y.values

In [22]:
from sklearn.model_selection import train_test_split

In [23]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 41 )